### ISSUE TITLE
Anime and search not working

### ISSUE THREAD

**Issue by Degeurige** [SirTakoyaki/Masterani#2]
when cklicking on Anime or search button I can select or input what I want, after applying nothing happens.
This error only in Kodi 18  fresh install. (i know still beta)
On Kodi 17.6 fresh install All is working 100%.
I can't find why, any suggestions?

**Comment by nicmr** [comment]
For me, it doesn't work on Kodi 17.6 either.

**Comment by SirTakoyaki** [comment]
At this point in time, I'm not sure what the issue may be on Kodi 18, as I'm pretty unfamiliar with it. My guess is that they changed something in the new version that is causing it to hang. My suggestion for now is to avoid using Masterani on 18, especially since it's on Alpha 2. Once a public release is out, if it still continues to not work, I'll try and take a closer look.

As for @nicmr , there might be an application running that's causing it to not work properly? I'm still on 17.6 and it works well (even on a fresh install). Try closing some background applications to see if anything is conflicting; I encountered an issue before where search wasn't working while I had Adguard running (it took me so long to figure this out, but it was blocking the network connection somewhere), so see if your device is running a similar app that might be blocking the connection. Otherwise, my next suggestion would be to take at your network to make sure it's not blocking it.

**Comment by Degeurige** [comment]
ok thanks for the answer, and the great work.

**Comment by nicmr** [comment]
@SirTakoyaki sorry, my previous comment was somewhat useless, please let me document the issue in more detail.
### Problem description
- *Anime*,  *Popular today* and *Search* don't work - instead, they show a popup: "Masterani Error, Check the log for more Information"
Could you point me to the location of the log file? I checked
```.kodi/userdata/addon_data/plugin.video.masterani/```
but theres no log file to be found, only .db files and the settings.xml

- *Recent* and *Last Played* work perfectly (so I doubt it's a network-related issue)

### System information:
Kodi 17.6 on Fire TV Stick
#### Other installed addons:
- Indigo
- Covenant
- (neither of them running, both unlikely to interfere with Masterani imo)

If you want, I can move this to a separate issue so this one can be kept related to Kodi 18-related issues (and change this issues title accordingly).

**Comment by SirTakoyaki** [comment]
Moving this as a separate issue would be best. Logs for the Android can be found under .kodi/temp/kodi.log. Make sure to enable debug logging in the settings under "Logging" as well. Just to double check, you're using v1.0.4 of the addon? Is PyXBMCt enabled under settings -> addons -> manage dependencies?

**Comment by ghost** [comment]
Fix:

Comment or remove the following lines as Container.Update seems to be broken in Kodi 18

https://github.com/SirTakoyaki/Masterani/blob/28e6c7ad841ee6909bc403ffb08dfeb85b5c379a/resources/lib/indexers/animeshows.py#L190-L192

**Comment by SirTakoyaki** [comment]
Thanks for investigating! @Degeurige, if you plan on still using the addon on Kodi 18, try removing the lines mentioned by @hoppler as a temporary solution. If the public release doesn't fix Container.Update (or it becomes depreciated) then I'll be making those changes in the next version.

**Comment by ghost** [comment]
As there is no reason for Container.Update you can remove it for all versions i guess.
